#Role variabelen voor beat
beats_config_file: "files/metricbeatWeb.yml"

#Variabelen voor Drupal en Drush
#admin kww545k
drupal_database: 'drupal'
drupal_username: 'stephan'
drupal_password: 'Test12345'
drupal_database_host: '192.168.56.10'
drupal_prefix: ''