# group_vars/all.yml
# Variables visible to all nodes
---
#Role variabelen voor rhbase
rhbase_repositories:
  - epel-release

rhbase_firewall_allow_services:
  - http
  - https
  - elasticsearch
  - mysql
  
rhbase_firewall_allow_ports:
  - 9200/tcp
  - 5601/tcp
  
rhbase_firewall_interfaces:
  - enp0s3
  - enp0s8
  
rhbase_user_groups:
  - users

rhbase_users:
  - name: stephan
    comment: Administrator
    groups: 
      - users
      #Encryptie: crypt-sha512
    password: '$6$0C9FrU8V7CmI3xdy$IZ8hAEcMVf9EQUZrW5pBC2WQZHwkcGKpp7qKKbgsEs2d1fR63or/s3k1Vu8fbwHvcaLo67QQ8s/twoXzEq87d1'
  
httpd_scripting: 'php'

#Role variabelen voor beat
metricbeat_user: stephan
metricbeat_group: users
metricbeat_create_user: true